#!/usr/bin/env ruby

`git submodule init && git submodule sync && git submodule update`
`git submodule update --init --recursive`

# updating the submodules: git submodule foreach git pull origin master

# inspired by http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
  next if file =~ /install/
  target = File.join(home, ".#{file}")
  if File.exists? target then
    if File.symlink? target then
      puts "Skipping .#{file} (already installed)"
    else
      puts "Skipping .#{file} (already exists)"
    end
    next
  end
  puts "Installing .#{file}"
  `ln -s #{File.expand_path file} #{target}`
end

puts "Update vim docs"
system "vim -e -s <<-EOF\n:Helptags\n:quit\nEOF"
