export PATH=~/bin:$PATH
export LANG=en_US.UTF-8
if [[ "$VENDOR" == "apple" ]]; then
	export PATH=~/bin/osx:$PATH
	export PATH=/usr/local/bin:$PATH
	export PATH=/usr/local/sbin:$PATH
fi

PATH=$PATH:~/.rvm/bin # Add RVM to PATH for scripting

[ -f ~/.zshenv-local ] && source ~/.zshenv-local
